#!/usr/bin/env bash
# script that transfers a file
PATH_TO_TRANSFER_FILE=$1
IP=$2
USERNAME=$3
PATH_TO_SSH_KEY=$4
if [ "$#" -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -o StrictHostKeyChecking=no -i "$PATH_TO_SSH_KEY" "$PATH_TO_TRANSFER_FILE" "$USERNAME"@"$IP":~/
fi
