#!/usr/bin/env bash
# Show PID

argc=$#
if [ "$argc" -ne 1 ]; then
    echo "Usage: manage_my_process {start|stop|restart}"
else
    case ${1} in
        "start")
            (./manage_my_process) &
            echo $$ > my_process.pid
            sudo mv my_process.pid /var/run/
            echo "manage_my_process started"
            ;;
        "stop")
            pkill -f ./manage_my_process
            sudo rm /var/run/my_process.pid
            echo "manage_my_process stopped"
            ;;
        "restart")
            pkill -f ./manage_my_process
            sudo rm /var/run/my_process.pid
            (./manage_my_process) &
            echo $$ > my_process.pid
            sudo mv my_process.pid /var/run/
            echo "manage_my_process restarted"
            ;;
        *) echo "Usage: manage_my_process {start|stop|restart}"
    esac
fi
